dataset_name: CarperAI/openai_summarize_comparisons
model_name_or_path: meta-llama/Meta-Llama-3.1-8B-Instruct
per_device_train_batch_size: 2
per_device_eval_batch_size: 4
learning_rate: 5.0e-6
gradient_accumulation_steps: 4
num_train_epochs: 1
logging_steps: 10
eval_strategy: steps
eval_steps: 200
save_strategy: steps
save_steps: 400
run_name: l31-8b-tldr-dpo-chat
output_dir: outputs/l31-8b-tldr-dpo-chat
warmup_ratio: 0.1
remove_unused_columns: False
report_to: wandb
bf16: True
dataset_num_proc: 32

use_peft: True
lora_r: 64
lora_alpha: 128
lora_dropout: 0.05
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj